# MySQL
spring: 
  datasource:
    url: bbMV8uoXbRxoBAPNZm0q1TI7eZKkQo1iqymIQvE8WTEMr+djHPfGG5RDJTNIMUxAPWkqwkEAPSrxNERQL4pXjPCac35S0cnr6a4tnTtbSv0nJdcxLX2zIh1Ul6rjG2Zt0gNw+wHwYMOCF/vTHUtjlA==

##JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: update

# logging  
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug
        
# Security
#  security:
#    user:
#      name: user
#      password: user



