# MySQL
spring: 
  datasource:
    url: jdbc:mysql://bb422509e54283:f3a5cba8@us-cdbr-east-02.cleardb.com/heroku_5d75bfaa6eeb92c?reconnect=true
 
#  datasource:
#   url: jdbc:mysql://localhost:3306/carros?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: eita


##JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: update

# logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug
        
# Security
#  security:
#    user:
#      name: jande
#      password: jandao



