# MySQL
spring: 
  datasource:
    url: KRwP4RRIo/Xx8kfuKjWWOMDIA1iRM0xQVRDKOBKMjMaTJnVs7ltY6f31cGeuVcFdWINST8dvnI97NW4a3pARwpV0c9znr/+CZE8wqbycMxNvJLos4GaYecc3YzSG6e1gcmcCFR6h2J209dO763GL3g==

##JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: update

# logging  
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug
        
# Security
#  security:
#    user:
#      name: user
#      password: user



